// <auto-generated />
using System;
using Gestion_Fimas_Digitales.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Gestion_Fimas_Digitales.Migrations
{
    [DbContext(typeof(Db_context))]
    [Migration("20241027213311_postgresql_migration_762")]
    partial class postgresql_migration_762
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Gestion_Fimas_Digitales.Models.FirmaDigital", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_firma");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CertificadoDigital")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("certificado_digital");

                    b.Property<string>("EmpresaAcreditadora")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("empresa_acreditadora");

                    b.Property<DateTime>("FechaEmision")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_emision");

                    b.Property<DateTime>("FechaVencimiento")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_vencimiento");

                    b.Property<string>("RazonSocial")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("razon_social");

                    b.Property<string>("RepresentanteLegal")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("representante_legal");

                    b.Property<string>("RutaRubrica")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ruta_rubrica");

                    b.Property<char>("TipoFirma")
                        .HasColumnType("character(1)")
                        .HasColumnName("tipo_firma");

                    b.HasKey("Id");

                    b.ToTable("firmaDigital");
                });
#pragma warning restore 612, 618
        }
    }
}
